### ISSUE TITLE
有没有配置教程啊，支持windows吗

### ISSUE THREAD

**Issue by yanggg1133** [GenialX/PHP-CPP-documentation#1]
我把phpcpp的include 程序复制到这里
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\phpcpp
---------------------------------------
vc11 命令行 
cl main.cpp 出现下面错误
---------------------------------------
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\xlocale(341): war
ning C4530: 使用了 C++ 异常处理程序，但未启用展开语义。请指定 /EHsc
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\phpcpp/inivalue.h
(18): error C2079: “IniValue”使用未定义的 class“Php::PHPCPP_EXPORT”
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\phpcpp/inivalue.h
(19): error C2059: 语法错误:“public”
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\phpcpp/inivalue.h
(26): error C2143: 语法错误: 缺少“;”(在“{”的前面)
-------------------------------------

**Comment by huxiaoxu2019** [comment]
您好，这个库只是文档的中文翻译。如果关于PHP-CPP的问题，建议您到官方库进行提交issue。https://github.com/CopernicaMarketingSoftware/PHP-CPP
